spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/policy
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## Freemarker 配置
## 文件配置路径
  freemarker:
    template-loader-path:classpath: /templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
##redis
#  redis:
#    database: 9
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0
logging:
  file: vote.log
  path: ./
  level: debug